#:import menu menu

MainWidget:




<MainWidget>:
    canvas.before:
        Rectangle:
            size: self.size
            source: "images/bg1.jpg"

    menu_widget: menu_widget
    perspective_point_x: self.width/2
    perspective_point_y: self.height * 0.75
    MenuWidget:
        id: menu_widget
    Label:
        text: root.score_text
        size_hint: 0.2, 0.2
        pos_hint: {"x": 0, "top": 1}
        font_size: dp(40)
        font_name: 'fonts/Eurostile.ttf'
    